### ISSUE TITLE
Door connected rooms are all empty

### ISSUE THREAD

**Issue by aknobloch** [aknobloch/An-Endless-Night#20]
Inside every Room, there is an array of Doors. Inside every door, there is supposed to be an array of connected rooms (probably just size two). 

As of now, the array of connected rooms are empty. This makes it impossible to move to any rooms. This is urgent, please fix!

**Comment by aknobloch** [comment]
@Jory1110 on second look, the bug could be originating from your method in the Door class.

Why are we even storing these as ID's and not just references to the rooms? Seems super inefficient.

**Comment by Jory1110** [comment]
Thats what was in the class diagram if we made doors hold their connected rooms that would be awesome.



Sent from my Sprint Samsung Galaxy Note5.


-------- Original message --------

**Comment by aknobloch** [comment]
Yea let's look into that. I'll try to refactor in a bit. It's going to require a lot of changes in @EstephanieGonzalez 's RoomLibrary, though.

**Comment by aknobloch** [comment]
Fixed. Door.getConnectedRooms() still loops through everything, but it was way too hard to try and refactor everything.
