### ISSUE TITLE
[Optional] RoomLibrary

### ISSUE THREAD

**Issue by aknobloch** [aknobloch/An-Endless-Night#21]
The RoomLibrary is getting pretty out of control. 600+ lines of code is making it near impossible to manage and a pain to debug. Can we please look into refactoring this to load rooms dynamically instead of having everything hardcoded? The entire class should be able to be written in less than 100 lines, easy. 

This isn't urgent, but would make life easier.

**Comment by EstephanieGonzalez** [comment]
If I can get to the AEC today at 3 I'd like to work on doing that. Hard coding it took a while and I'd like to have a better way of doing this.

**Comment by aknobloch** [comment]
Too late for this. Closing.
