### ISSUE TITLE
monster encounter, score, and health

### ISSUE THREAD

**Issue by EstephanieGonzalez** [aknobloch/An-Endless-Night#28]
After an encounter with Maneki-Neko I killed the monster and when I viewed score after it still read 0. We should also have a way of viewing player health because it's unclear to the player what they're starting with and ending with.

**Comment by aknobloch** [comment]
I'm unclear how the point system is supposed to work. I can add the health feature, though. Will be very easy to implement both.

**Comment by aknobloch** [comment]
For now, I've made it that the score added to the Game is equal to however much strength that monster had. Seems fair, but could be better.

**Comment by CalebCrosbySears** [comment]
I changed the strength of Maneki-Neko to 1.

**Comment by aknobloch** [comment]
@CalebCrosbySears the strength of Maneki-Neko should stay at zero, that's in the reqts spec. The score issue that estephanie was talking about is fixed, however maneki-neko should not add any to the score anyways so this is okay.
