### ISSUE TITLE
Help guide

### ISSUE THREAD

**Issue by aknobloch** [aknobloch/An-Endless-Night#29]
Not really sure what to have for this....need suggestions, please comment.

**Comment by aknobloch** [comment]
So, I've removed the help system entirely. I really just can't figure out what the hell would possibly need to go in it. The commands are all numerical. I know she said that we should have a help option, but we can probably get away with saying the journal is the help system? I don't know....if we want to do a help system it will be super easy to implement, but I need to know what the hell to even put in it.

**Comment by CalebCrosbySears** [comment]
I don't know either... maybe a map of where the player has been already. or we could make the journal add its own entries in the game. so the player has some direction of where to go at all times.

**Comment by aknobloch** [comment]
New issue opened for this.
