### ISSUE TITLE
Tengu Not dropping anything....

### ISSUE THREAD

**Issue by aknobloch** [aknobloch/An-Endless-Night#50]
@CalebCrosbySears title says it all. Please address, thanks!

**Comment by CalebCrosbySears** [comment]
The items are in Tengu's itme drop arrayList. Are any of the monsters dropping anything? I can't find where the method that handles this is. Are the monsters dropping the items in the rooms or in the players inventory?

**Comment by aknobloch** [comment]
Fixed.
