### ISSUE TITLE
Kitsune’s Tail gives you health after monster attacks

### ISSUE THREAD

**Issue by CalebCrosbySears** [aknobloch/An-Endless-Night#59]
originally had 99 health
It attacks you, leaving you with 1421 health left.
It attacks you, leaving you with 2743 health left.

**Comment by aknobloch** [comment]
Wait how are you even getting Kitsune's tail. I haven't finished coding the Kitsune fight.

**Comment by CalebCrosbySears** [comment]
its in the south garden

**Comment by aknobloch** [comment]
This was fixed.
