### ISSUE TITLE
What to do if Hero dies?

### ISSUE THREAD

**Issue by aknobloch** [aknobloch/An-Endless-Night#6]
We need to handle case if Hero dies. Not sure how to implement this, relies heavily on how the Menu system will operate. In DamageHandler.attackHero().

**Comment by Jory1110** [comment]
If the hero dies we reload last save



Sent from my Sprint Samsung Galaxy Note5.


-------- Original message --------

**Comment by aknobloch** [comment]
Yea, but idk how to implement that. First we have to alert the combat menu boundary object, and then maybe take them back to the main menu?

**Comment by aknobloch** [comment]
Finished. Outputs a message, and opens up the main menu. Fixed in commit 7b3156a5ec4decd2bb4e7a93cd4d9dd7b62a38d7
