### ISSUE TITLE
The game stops working if you enter in a command to fast. The game still runs but will not allow you to move forward or enter commands

### ISSUE THREAD

**Issue by EstephanieGonzalez** [aknobloch/An-Endless-Night#66]
![screenshot 154](https://cloud.githubusercontent.com/assets/16963676/20320816/36b34e34-ab41-11e6-89c0-298eabf7b683.png)

**Comment by aknobloch** [comment]
I couldn't recreate this issue? Same thing, but it allowed me to enter new input.

![capture](https://cloud.githubusercontent.com/assets/9557120/20321457/874bf20e-ab43-11e6-8aa3-f9bfa77e52f0.PNG)

**Comment by aknobloch** [comment]
I'm closing this. I think maybe it was PICNIC error :P
